### ISSUE TITLE
Add Avro doc field ?

### ISSUE THREAD

**Issue by mredjem** [artur-tamazian/avro-schema-generator#22]
Hi,

Are there any plans to add the Avro doc field to the schema and its fields ?

I'm looking to generate Avro schemas on the fly and document each field based on the SQL comments.
I've been able to successfully generate a documented schema based on what SchemaCrawler fetched.

I made a small development on a local branch to test it out.

**Comment by artur-tamazian** [comment]
Hi Medhi!

Would you like to send a PR or share the SchemaCrawler code you've used? I can help you prepare a pull request if you'd like to contribute.

**Comment by mredjem** [comment]
I added the feature on my side on a forked repository so I can quickly create a PR.
Do you have guidelines you expect me to follow ?

**Comment by artur-tamazian** [comment]
Nothing specific - try to follow the same formatting you see in the existing code and please add a unit test if that's not too time-consuming.  Thanks!

**Comment by mredjem** [comment]
Hi Artur,
I created the PR #23 for you to review.

**Comment by artur-tamazian** [comment]
I just submitted your PR and released a new version (1.0.6) that contains it. Thanks a lot for the contribution!
