### ISSUE TITLE
Slow performance with schema containing large number of tables

### ISSUE THREAD

**Issue by ofirgrm** [artur-tamazian/avro-schema-generator#28]
Running the following code with latest version (1.0.7) doesn't seems to provide results within reasonable amount of time on schema containing large number of tables (~650): 

```
        DbSchemaExtractor schemaExtractor = new DbSchemaExtractor("jdbc:mysql://XXX", "XXX", "XXX");
        AvroConfig avroConfig = new AvroConfig("XXX");
        List<AvroSchema> schemas = schemaExtractor.getForTables(avroConfig, "MY_SCHEMA", "MY_TABLE");
```

I have substitute the actual values with either XXX or MY_....

This code intends to fetch the AvroSchema object for a **single** table, however, it seems that in the background the code iterate over all the tables.
I have run this code and stopped it after 30 minutes of execution. it was spewing out lots of logs similar to this:

```
Jun 07, 2021 1:21:31 PM schemacrawler.crawl.ResultsCrawler crawl
INFO: Crawling result set
Jun 07, 2021 1:21:31 PM schemacrawler.crawl.ResultsCrawler crawl
INFO: Total time taken for <crawlResultSet> - 00:00:00.005 hours
-100.0% - 00:00:00.005 - <retrieveResults>
```

Having a DB with around 500-700 tables, is a typical use case for a medium monolitch software and itsn't reasonable that it takes more than a minute to produce Avro schema for a single table.

**Comment by artur-tamazian** [comment]
Thanks for reporting! You're right, currently, the tool does go over all the tables. 
I should be able to fix this - will try to get to it in the next couple of days.

**Comment by ofirgrm** [comment]
That's great! thanks for the prompt response

**Comment by artur-tamazian** [comment]
I've made a change to speed up the getForTable() method (the one that takes a single table name as an argument). Hope this works for your case. If you need several tables - try calling this method several times for each of them.

I wish I could fix this in a more general way but I'm limited by the SchemaCrawler library that is used.

The new "1.0.8" version contains this fix. It might take some time but it should become available in the repository soon 
(check [here](https://search.maven.org/artifact/com.github.artur-tamazian/avro-schema-generator)).

**Comment by ofirgrm** [comment]
Thanks, this fix does help. I'm running it for 3 tables and it takes around a minute to produce the schema.
BTW, when I use Avro maven plugin to generate the classes it gives me the following warnings:
```
[WARNING] Ignoring invalid logical type for name: timestamp-millis
[WARNING] Ignoring invalid logical type for name: decimal

```
it doesn't seem to affect the generated classes, but I thought it's worth mentioning

**Comment by artur-tamazian** [comment]
Thanks for confirming! A minute still sounds too slow but it might be db specific (load, connection latency, etc). As for the warnings - quick googling suggests that there are fixes for it via Avro lib that maven plugin uses.
