### ISSUE TITLE
Update SchemaCrawler

### ISSUE THREAD

**Issue by tqigbarboza** [artur-tamazian/avro-schema-generator#34]
I want to suggest updating the shemaCrawler and checking the error unknown data type: number when trying to generate avro from an Oracle database

**Comment by artur-tamazian** [comment]
Hi, sorry for the late reply!

Is this still an issue for you? If it is, I can try upgrading the crawler. Would you be able to provide me a `desc table_name` output so I can try to reproduce it? If you can send a pull request with a test for this issue it would be even better (and much appreciated!).
