### ISSUE TITLE
[proposal] Migrate build to Gradle

### ISSUE THREAD

**Issue by eshepelyuk** [artur-tamazian/avro-schema-generator#9]
Would you mind migrating the project to `Gradle`, so one can leverage `Travis CI` cache and reduce build \ test time ?

**Comment by artur-tamazian** [comment]
First I'd like to fix the Travis build in general (https://travis-ci.org/artur-tamazian/avro-schema-generator) It started failing after java update so fix should be easy.

After that, I might look into migrating if I have time. Builds should be quite fast already, right?

**Comment by eshepelyuk** [comment]
Hi @artur-tamazian 
My proposal implies my involvement and contribution. I.e. I'm gonna take care of the migration and providing PR
